alias ls='ls --color=auto'
alias emacs='emacsclient -nc'
export EDITOR=emacs
# eval "$(stack --bash-completion-script stack)"
source /usr/share/git/completion/git-completion.bash
PATH_ADDITIONAL=:/home/nchashch/.cargo/bin:/home/nchashch/.local/bin
export PATH=$PATH$PATH_ADDITIONAL
